---
# Source: essentry-auth/charts/oauth2-proxy/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-3.2.1
    heritage: Tiller
    release: oauth2-proxy-dev
  name: oauth2-proxy-dev
type: Opaque
data:
  cookie-secret: "WFhYWFhYWFhYWA=="
  client-secret: "WFhYWFhYWFg="
  client-id: "WFhYWFhYWA=="
---
# Source: essentry-auth/charts/oauth2-proxy/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-3.2.1
    heritage: Tiller
    release: oauth2-proxy-dev
  name: oauth2-proxy-dev
data:
  oauth2_proxy.cfg: "email_domains = [ \"*\" ]\nupstreams = [ \"file:///dev/null\" ]"

---
# Source: essentry-auth/charts/oauth2-proxy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-3.2.1
    release: oauth2-proxy-dev
    heritage: Tiller
  name: oauth2-proxy-dev
---
# Source: essentry-auth/charts/oauth2-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-3.2.1
    release: oauth2-proxy-dev
    heritage: Tiller
  name: oauth2-proxy-dev
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: oauth2-proxy
    release: oauth2-proxy-dev

---
# Source: essentry-auth/charts/oauth2-proxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
    chart: oauth2-proxy-3.2.1
    heritage: Tiller
    release: oauth2-proxy-dev
  name: oauth2-proxy-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
      release: oauth2-proxy-dev
  template:
    metadata:
      annotations:
        checksum/config: 33d77aae6fd418fe7a8654d866a644e71eb174e01a7d1284087b5025645af295
        checksum/config-emails: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/secret: 45914a309f52362a10850b6dc50b88875e424b05a1ecca270d88dd9005dc107f
        checksum/google-secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      labels:
        app: oauth2-proxy
        release: "oauth2-proxy-dev"
    spec:
      serviceAccountName: oauth2-proxy-dev
      containers:
      - name: oauth2-proxy
        image: "quay.io/pusher/oauth2_proxy:v5.1.0"
        imagePullPolicy: IfNotPresent
        args:
          - --http-address=0.0.0.0:4180
          - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy-dev
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy-dev
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy-dev
              key: cookie-secret
        ports:
          - containerPort: 4180
            name: http
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
          successThreshold: 1
          periodSeconds: 10
        resources:
          {}
          
        volumeMounts:
        - mountPath: /etc/oauth2_proxy
          name: configmain
      volumes:
      - configMap:
          defaultMode: 420
          name: oauth2-proxy-dev
        name: configmain
      tolerations:
        []
        

---
# Source: essentry-auth/charts/oauth2-proxy/templates/configmap-authenticated-emails-file.yaml


---
# Source: essentry-auth/charts/oauth2-proxy/templates/configmap-htpasswd-file.yaml

---
# Source: essentry-auth/charts/oauth2-proxy/templates/google-secret.yaml

---
# Source: essentry-auth/charts/oauth2-proxy/templates/ingress.yaml

---
# Source: essentry-auth/charts/oauth2-proxy/templates/poddisruptionbudget.yaml


